#!/usr/bin/env node

/**
 * Module dependencies.
 */
 let app = require('../app_cron');
let debug = require('debug')('e-commerce-node:server');
let models = require("../models");


/**
 * Listen on provided port, on all network interfaces.
 */

models.sequelize.authenticate().then(function () {
  onListening()
}).catch(err => {
  onError(err)
});


/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  let bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  debug('Connected successfully!');
}
